collections:
  authors:
    output: true
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "about"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/blog/posts/:year/:month/:day/:title:output_ext"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/data"
    values:
      layout: "json"
  - scope:
      path: "_pages/about"
      type: "pages"
    values:
      layout: "page"
      permalink: "/about/:name:output_ext"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      titleOnly: true
      layout: "page"